export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/1.jpeg",
        username: "Jack Sprat",
    },
    {
        id: 2,
        profilePicture: "assets/person/2.jpeg",
        username: "Bill Glen",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpeg",
        username: "Bob Law",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpeg",
        username: "Kim Hall",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Susan Ma",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpeg",
        username: "June Jones",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpeg",
        username: "Han Lat",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpeg",
        username: "James Brown",
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpeg",
        username: "Mark Black",
    },
    {
        id: 10,
        profilePicture: "assets/person/10.jpeg",
        username: "Jim White",
    },

];

export const Posts = [
    {
        id: 1,
        desc: "Hello World",
        photo: "assets/post/1.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 40,
        comment: 3,
    },
    {
        id: 2,
        desc: "Hello World 2",
        photo: "assets/post/2.jpeg",
        date: "25 mins ago",
        userId: 2,
        like: 40,
        comment: 3,
    },
    {
        id: 3,
        desc: "Hello World 3",
        photo: "assets/post/3.jpeg",
        date: "9 hours ago",
        userId: 3,
        like: 20,
        comment: 4,
    },
    {
        id: 4,
        desc: "Hello World 4",
        photo: "assets/post/4.jpeg",
        date: "6 hours ago",
        userId: 4,
        like: 10,
        comment: 1,
    },
    {
        id: 5,
        desc: "Hello World 5",
        photo: "assets/post/5.jpeg",
        date: "6 days ago",
        userId: 5,
        like: 12,
        comment: 4,
    },
    {
        id: 6,
        desc: "Hello World 6",
        photo: "assets/post/6.jpeg",
        date: "10 days ago",
        userId: 6,
        like: 20,
        comment: 13,
    },
    {
        id: 7,
        desc: "Hello World 7",
        photo: "assets/post/7.jpeg",
        date: "7 mins ago",
        userId: 7,
        like: 4,
        comment: 15,
    },
    {
        id: 8,
        desc: "Hello World 8",
        photo: "assets/post/8.jpeg",
        date: "7 days ago",
        userId: 8,
        like: 4,
        comment: 2,
    },
    {
        id: 9,
        desc: "Hello World 9",
        photo: "assets/post/9.jpeg",
        date: "9 hours ago",
        userId: 9,
        like: 11,
        comment: 11,
    },
    {
        id: 10,
        desc: "Hello World 10",
        photo: "assets/post/10.jpeg",
        date: "10 mins ago",
        userId: 10,
        like: 10,
        comment: 10,
    },   
]